language: rust

before_install:
  - git clone https://github.com/eldruin/rust-driver-example-ci-scripts ci
  - bash ci/before_install.sh

env:
  global:
    - DRIVERS="
            ad983x
            ads1x1x
            apds9960
            bmi160
            ds1307
            ds323x
            eeprom24x
            embedded-ccs811
            hdc20xx
            isl29125
            kxcj9
            lm75
            max170xx
            max3010x
            max44009
            mcp4x
            mcp49xx
            mcp794xx
            mlx9061x
            mma8x5x
            opt300x
            pcf857x
            pwm-pca9685
            tcs3472
            tmp006
            tmp1x2
            veml6030
            veml6075
            xca9548a"

# veml6040 Git version is not compatible. Deactivated until a new version is released.
# veml6070 Git version is not compatible. Deactivated until a new version is released.

matrix:
  include:
    - env: TARGET=thumbv7em-none-eabihf SUBFOLDER=stm32f3-discovery

    - env: TARGET=thumbv7em-none-eabihf SUBFOLDER=stm32f3-discovery
      rust: nightly

    - env: TARGET=thumbv7m-none-eabi SUBFOLDER=stm32f1-bluepill

    - env: TARGET=thumbv7m-none-eabi SUBFOLDER=stm32f1-bluepill
      rust: nightly

    # Minimum Supported Rust Version
    # Deactivated until this fix is released:
    # https://github.com/jamwaffles/embedded-graphics/pull/76
    #- env: TARGET=thumbv7em-none-eabihf
    #  rust: 1.31.0

    - env: TARGET=thumbv7em-none-eabihf GIT_DRIVERS=$DRIVERS SUBFOLDER=stm32f3-discovery

    - env: TARGET=thumbv7em-none-eabihf GIT_DRIVERS=$DRIVERS SUBFOLDER=stm32f3-discovery
      rust: nightly

    - env: TARGET=thumbv7m-none-eabi GIT_DRIVERS=$DRIVERS SUBFOLDER=stm32f1-bluepill

    - env: TARGET=thumbv7m-none-eabi GIT_DRIVERS=$DRIVERS SUBFOLDER=stm32f1-bluepill
      rust: nightly

    # Minimum Supported Rust Version
    #- env: TARGET=thumbv7em-none-eabihf GIT_DRIVERS=$DRIVERS
    #  rust: 1.31.0

install:
  bash ci/install.sh

script:
  bash ci/script.sh

after_script: set +e

cache: cargo
cache:
  directories:
    - /home/travis/.cargo

before_cache:
  bash ci/before_cache.sh

notifications:
  email:
    on_success: never
