language: rust

before_install:
  - git clone https://github.com/eldruin/rust-driver-example-ci-scripts ci
  - bash ci/before_install.sh

matrix:
  include:
    # F3 Discovery
    - env: TARGET=thumbv7em-none-eabihf

    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly

    # Minimum Supported Rust Version
    - env: TARGET=thumbv7em-none-eabihf
      rust: 1.31.0

install:
  bash ci/install.sh

script:
  bash ci/script.sh

after_script: set +e

cache: cargo
cache:
  directories:
    - /home/travis/.cargo

before_cache:
  bash ci/before_cache.sh

notifications:
  email:
    on_success: never
