on: [push, pull_request]

name: Code formatting check

jobs:
  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SUBFOLDER:
          - stm32f3-discovery
          - stm32f1-bluepill
          - microbit
          - raspberrypi

    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            - ~/.cargo/bin/
            - ~/.cargo/registry/index/
            - ~/.cargo/registry/cache/
            - ~/.cargo/git/db/
          key: ${{ runner.OS }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.OS }}-cargo-

      - name: Cache build output dependencies
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.OS }}-build-

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - run: cargo fmt --all -- --check
        working-directory: ${{ matrix.SUBFOLDER }}
